{
 "title": "MSK & KEDA Monitoring",
 "tags": [
  "kafka",
  "keda",
  "msk"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka Inbound Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\", topic=\"trade-tx-v2\"}[$__rate_interval]))",
     "legendFormat": "MessagesInPerSec"
    }
   ]
  },
  {
   "title": "Consumer Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_messages_processed_total[$__rate_interval]))",
     "legendFormat": "Messages/sec"
    }
   ]
  },
  {
   "title": "Kafka Partition Offset Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "msg" } },
   "targets": [
    {
     "expr": "kafka_consumer_group_ConsumerLagMetrics_Value{topic=\"trade-tx-v2\", name=\"MaxOffsetLag\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{}",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Message Time in Kafka",
   "type": "timeseries",
   "description": "Aggregated time messages stay in Kafka queue, from push to Kafka to poll by consumer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_message_age_seconds_sum[5m])) / sum(rate(kafka_message_age_seconds_count[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Consumer Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{}",
     "legendFormat": "Current"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{}",
     "legendFormat": "Desired"
    }
   ]
  },
  {
   "title": "Ready Nodes Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "Ready Nodes"
    }
   ]
  }
 ]
}